site_name: sudoku-tools
nav:
  - Overview: README.md
  - Documentation: documentation.md
repo_url: https://github.com/dawsonbooth/sudoku-tools/
site_url: https://dawsonbooth.github.io/sudoku-tools/

markdown_extensions:
  - toc:
      permalink: 🔗

theme:
  name: readthedocs

plugins:
  - mkdocstrings
